/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ktu.agveri.crypt;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author mcanv
 */
public class MainReceiverGui extends javax.swing.JFrame {

    
            private String Inputfile;
            private String imzaPath;

    /**
     * Creates new form MainReceiverGui
     */
    public MainReceiverGui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        decryptedLabel = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        openFile = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        openImzaPath = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        hashLabel = new javax.swing.JTextArea();
        decryptButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        hashle = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        OpenImza = new javax.swing.JMenuItem();
        OpenFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gelen İmzalı Dosya");

        decryptedLabel.setColumns(20);
        decryptedLabel.setRows(5);
        jScrollPane2.setViewportView(decryptedLabel);

        openFile.setColumns(20);
        openFile.setRows(5);
        jScrollPane3.setViewportView(openFile);

        openImzaPath.setColumns(20);
        openImzaPath.setRows(5);
        jScrollPane4.setViewportView(openImzaPath);

        hashLabel.setColumns(20);
        hashLabel.setRows(5);
        jScrollPane5.setViewportView(hashLabel);

        decryptButton.setText("Decrypt");
        decryptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decryptButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Gelen Dosya");

        hashle.setText("Hashle");
        hashle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hashleActionPerformed(evt);
            }
        });

        jButton3.setText("Sonuc");

        jLabel3.setText("True/False");

        jMenu1.setText("File");

        OpenImza.setText("Gelen İmzalı Dosyayi Aç");
        OpenImza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenImzaActionPerformed(evt);
            }
        });
        jMenu1.add(OpenImza);

        OpenFile.setText("Gelen Dosya");
        OpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenFileActionPerformed(evt);
            }
        });
        jMenu1.add(OpenFile);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addComponent(decryptButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hashle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane3)
                            .addComponent(jScrollPane5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jButton3)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decryptButton))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hashle))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel3))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenImzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenImzaActionPerformed
        // TODO add your handling code here:
         int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try{
                openImzaPath.read(new FileReader(file.getAbsoluteFile() ), null);
                openImzaPath.setText(file.getAbsolutePath());
                imzaPath = file.getAbsolutePath();
            }catch(IOException ex){
               // System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        }else {
          //  System.out.println("File access cancelled by user");
        }
    }//GEN-LAST:event_OpenImzaActionPerformed

    private void decryptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decryptButtonActionPerformed
        // TODO add your handling code here:
        Decrypt de = new Decrypt();
        
                String inFile = "/home/mcanv/Downloads/AgVeriFiles/Decrypted.txt";
		String line = ""; 
		String text = "";
		try {
			FileReader reader = new FileReader(inFile); 
			BufferedReader bReader = new BufferedReader(reader);
			try {
				while ((line = bReader.readLine()) != null) {
					text = text + line;
				}
                                System.out.println(" reciever text :" +text);
                                decryptedLabel.setText(text);
				//System.out.println("doya okundu!");
				bReader.close();
			} catch (IOException e) {
				//System.out.println("Dosya okunamadı!");
			}

		} catch (FileNotFoundException e) {
			//System.out.println("Dosya bulunamadı!");
		}
    }//GEN-LAST:event_decryptButtonActionPerformed

    private void OpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenFileActionPerformed
        // TODO add your handling code here:
         int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try{
                openFile.read(new FileReader(file.getAbsoluteFile() ), null);
                openFile.setText(file.getAbsolutePath());
                Inputfile = file.getAbsolutePath();
            }catch(IOException ex){
               // System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        }else {
          //  System.out.println("File access cancelled by user");
        }
    }//GEN-LAST:event_OpenFileActionPerformed

    private void hashleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hashleActionPerformed
        // TODO add your handling code here:
         Md5Encryption md5 = new Md5Encryption();
       // System.out.println(Inputfile);
                String inFile =Inputfile;
		String line = ""; 
		String text = "";
		try {
			FileReader reader = new FileReader(inFile); 
			BufferedReader bReader = new BufferedReader(reader);
			try {
				while ((line = bReader.readLine()) != null) {
					text = text + line;
				}
				//System.out.println("doya okundu!");
				bReader.close();
			} catch (IOException e) {
				//System.out.println("Dosya okunamadı!");
			}

		} catch (FileNotFoundException e) {
			//System.out.println("Dosya bulunamadı!");
		}
                hashLabel.setText(md5.hash(text));
    }//GEN-LAST:event_hashleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainReceiverGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainReceiverGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainReceiverGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainReceiverGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MainReceiverGui().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem OpenFile;
    private javax.swing.JMenuItem OpenImza;
    private javax.swing.JButton decryptButton;
    private javax.swing.JTextArea decryptedLabel;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JTextArea hashLabel;
    private javax.swing.JButton hashle;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea openFile;
    private javax.swing.JTextArea openImzaPath;
    // End of variables declaration//GEN-END:variables
}
